server:
  port: 2458

spring:
  application:
    name: station-service
  datasource:
    url: jdbc:mysql://localhost:3306/station-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


#-------------------------------------------------
# swagger configurations
#-------------------------------------------------
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /station-service/v3/api-docs
  swagger-ui:
    enabled: false