server:
  port: 5874



spring:
  application:
    name: auth-service
  main:
    allow-circular-references: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true





springdoc:
  api-docs:
    groups:
      enabled: true
    path: /auth-service/v3/api-docs
  swagger-ui:
    enabled: false